# üíÅ The OpenShift CPE workflow will:
# - Parse inputs: service for deployment, namespace, helm-repo, command
# - Check for required secrets
# - Checkout your repository
# - Install OpenShift cli and helm chart tools
# - Add helm repository
# - Perform OpenShift cluster login
# - Perform helm install/install/validate for service

# ‚ÑπÔ∏è Configure your repository and the workflow with the following steps:
# 1. Have access to an OpenShift cluster. Refer to https://www.openshift.com/try
# 2. Create the OPENSHIFT_TOKEN and IMAGE_REGISTRY_TOKEN (optional HELM_REGISTRY_TOKEN) repository secrets. Refer to:
#   - https://github.com/redhat-actions/oc-login#readme
#   - https://docs.github.com/en/actions/reference/encrypted-secrets
#   - https://cli.github.com/manual/gh_secret_set
# 3. (Optional) Edit the top-level 'env' section as marked with 'üñäÔ∏è' if the defaults are not suitable for your project.
# 5. Commit and push the workflow file to your default branch. Manually trigger a workflow run.

# üìÉ Considerations
# Image registry should be added to cluster in coresponding namespace before workflow run
# Example:    
#     kubectl create secret docker-registry pullsecret \
#       --docker-server=repository.path \
#       --docker-username=user --docker-password=token
#     oc secrets link default pullsecret --for=pull



name: Deploy service

env:
  # üñäÔ∏è EDIT your repository secrets to log into your OpenShift cluster and set up the context.
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
  OPENSHIFT_SERVER:   "api.cluster.server.address:port"
  OPENSHIFT_TOKEN:     ${{ secrets.OPENSHIFT_TOKEN }}

  # üñäÔ∏è EDIT to change the helm registry settings.
  # Registries such as Jfrog, GHCR, Quay.io, and Docker Hub are supported.
  HELM_REGISTRY:           "https://repository.address/registry/"
  HELM_REGISTRY_USER:      ${{ secrets.HELM_REGISTRY_USER }}          
  HELM_REGISTRY_TOKEN:      ${{ secrets.HELM_REGISTRY_TOKEN }}


on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      service:
        description: service(s) for deployment
        required: true
        default: "webrtc"
      namespace:
        description: namespace (if not default)
        required: false
        default: "default"
      helmrepo:
        description: helm repo name in HELM_REGISTRY
        required: true
        default: helm-stage
      command:
        description: command install|validate|uninstall
        required: true
        default: validate
        
jobs:
  openshift-ci-cd:
    name: Build and deploy to OpenShift
     # üñäÔ∏è (Optional) EDIT if you want to run on your own runner
    runs-on: ubuntu-latest

    steps:
    - name: Check for required secrets
      uses: actions/github-script@v4
      with:
        script: |
          const secrets = {
            OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
            HELM_REGISTRY_TOKEN: `${{ secrets.HELM_REGISTRY_TOKEN }}`,
          };

          const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
            if (value.length === 0) {
              core.error(`Secret "${name}" is not set`);
              return true;
            }
            core.info(`‚úîÔ∏è Secret "${name}" is set`);
            return false;
          });

          if (missingSecrets.length > 0) {
            core.setFailed(`‚ùå At least one required secret is not set in the repository. \n` +
              "You can add it using:\n" +
              "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
              "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
              "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
          }
          else {
            core.info(`‚úÖ All the required secrets are set`);
          }


    - name: Check out repository
      uses: actions/checkout@v2


    - name: Install OC CLI tool for OpenShift
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        # üñäÔ∏è (Optional) EDIT if you want to specify oc cli version, for example "latest"
        oc: "latest"


    - name: Install helm tool
      uses: azure/setup-helm@v1
      with:
        # üñäÔ∏è (Optional) EDIT if you want to specify helm version (default: "latest")
        version: "v3.7.1"


    - name: Helm repo add
      run: |
        helm repo add --force-update helm_repo ${{ env.HELM_REGISTRY }}${{ github.event.inputs.helmrepo }} \
          --username ${{ env.HELM_REGISTRY_USER }} --password ${{ env.HELM_REGISTRY_TOKEN }}



    # https://github.com/redhat-actions/oc-login#readme
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token:      ${{ env.OPENSHIFT_TOKEN }}
        namespace:            ${{ github.event.inputs.namespace }}
        insecure_skip_tls_verify: true

    - name: Create or use project
      run: |
        NS=${{ github.event.inputs.namespace }}
        if ! oc project $NS; then
           echo "Project $NS does not exist. Creating it.."
           oc new-project $NS
        else
           echo "Project $NS already exists. Will use it."
        fi

    - name: Add rights to read secrets for default SA
      run: oc secrets link default pullsecret --for=pull

    - name: Custom script
      run: |
        export NS=${{ github.event.inputs.namespace }}
        export SERVICE=${{ github.event.inputs.service }}
        DOMAIN=${{ env.OPENSHIFT_SERVER }}
        export DOMAIN=$(echo $DOMAIN | sed 's/:.*//')

        cd $SERVICE

        # FOR EVERY HELM CHART ############################################################
        # ‚ÑπÔ∏è Notice: in application folder should be exist subfolder with name in format: 
        #      [0-9][0-9]_chart_chart-name 
        # where chart-name is name of chart using to installing 
        # and digits define the instalation order 
        # The chart-name using in command:
        #     helm install RELEASE-NAME helm-repo/chart-name
        # ##################################################################################
        for DIR in [0-9][0-9]_chart_*/; do
          
          CHART=$([[ -d "$DIR" ]] && echo $DIR | sed 's/[0-9][0-9]_chart_//' | sed 's/\///')
          
          DIR=$(echo $DIR | sed 's/\///')
          
          # evaluate ENV variables
          envsubst < $DIR/override_values.yaml > overrides.yaml

          # üñäÔ∏è (Optional) EDIT 1st line of chart.ver file with chart version number
          VER=$(head -n 1 $DIR/chart.ver)
          
          FLAGS="helm_repo/$CHART --install --version=$VER -n $NS -f $(pwd)/overrides.yaml"
          
          COMMAND=${{ github.event.inputs.command }}
          case $COMMAND in

            install)
              echo "Installing..."
              CMD="upgrade"
              ;;

            uninstall)
              echo "Uninstalling..."
              CMD="uninstall"
              FLAGS=""
              ;;

            validate)
              echo "Validating..."
              CMD="upgrade"
              FLAGS+=" --dry-run"
              ;;

            *)
              echo "‚ùå Wrong command"
              ;;

          esac

          cd $DIR
          
          touch overrides.yaml
          [[ "$FLAGS" ]] && FLAGS+=" -f $(pwd)/overrides.yaml"
            
          # FOR EVERY HELM RELEASE###########################################################
          # ‚ÑπÔ∏è Notice: in chart folder should be exist subfolder with name in format: 
          #      [0-9][0-9]_release_release-name 
          # where release-name is name of release using to installing 
          # and digits define the instalation order 
          # The release-name using in command:
          #     helm install release-name helm-repo/chart-name
          #
          # If you want to run some preparing script (for ex: init database, check conditions) 
          # before installing, place you code in pre-relese-script.sh in release subfolder
          #
          # If you want to run some post-installing script (for ex: validate something),
          # place you code in post-relese-script.sh in release subfolder
          # ##################################################################################
          for DIR_RL in [0-9][0-9]_release_*/; do

                RELEASE=$([[ -d "$DIR_RL" ]] && echo $DIR_RL | sed 's/[0-9][0-9]_release_//' | sed 's/\///')

                cd $DIR_RL
                # Run pre-release-script if exists
                [[ "$COMMAND" == "install" ]] && [[ -f "pre-release-script.sh" ]] \
                  && source pre-release-script.sh
                cd ..

                # evaluate ENV variables
                envsubst < $DIR_RL/override_values.yaml > overrides.yaml


                echo "helm $CMD $RELEASE $FLAGS"
                [[ "$CMD" ]] && [[ "$CHART" ]] && [[ "$RELEASE" ]] && \
                            helm $CMD $RELEASE $FLAGS

                cd $DIR_RL
                # Run post-release-script if exists
                [[ "$COMMAND" == "install" ]] && [[ -f "post-release-script.sh" ]] \
                  && source post-release-script.sh
                cd ..
          
          done

          cd ..

        done
