# no of instances to be created during starup default is 1
deployment:
  namespace: ${NS}
  replicaCount: 1

# override the registry from where the image will be deployed
image:
  registry: $IMAGE_REGISTRY
  pullPolicy: Always
  imagePullSecrets: "pullsecret"

# Set the redis port to be used. 
context:
  envs:
    redis:
      port: 6379

# Set the consul volume to be mounted
secrets:
  consulACL:
    volumes:
    - name: consul-shared-secret
      secret:
        secretName: consul-voice-token
  kafkaDC:                                                      # Mount secret for kafka Multi data center
    general:
      enabled: false
  kafka:                                                        # Mount secret for kafka single data center
    general:
      enabled: true 

# Enable HPA and set the target CPU and memory for scale up and down
hpa:
  targetCPUPercent: 60
  targetMemoryPercent: 60
  enabled: true 
