###############################################################################
# Global ucsx-addtenent image parameters
# https://all.docs.genesys.com/UCS/Current/UCSPEGuide/Provision
###############################################################################
tenant:
  id: ucsx_sid
  ccid: ucsx_tenant_id

gauth:
  auth:
    clientId: ucsx_gauth_client_id
    clientSecret: ucsx_gauth_client_secret
    regions: global_location

db:
  host: POSTGRES_ADDR
  ssl: false
  name: ucsx_tenant_db_name
  password: ucsx_tenant_db_password
  user: ucsx_tenant_db_user
  port: "5432"
  ssl: "false"