namespace: ${NS}
nameOverride: ""
fullnameOverride: ""

securityContext:
  runAsNonRoot: true
  runAsUser: 500
  runAsGroup: 500
  fsGroup: 500

podLabels: {}
podAnnotations: {}

wwe:
  image:
    registry: $IMAGE_REGISTRY
    repository: gws       
    name: gws-ui-workspace
    pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: pullsecret
  imagePullSecrets:
    - name: pullsecret
  service:
    enabled: true
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      # Example
       - host: wwe.${DOMAIN}
         paths:
           - path: '/'
             port: 80
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      #kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
    ingressClassName: nginx
    tls:
      # Example
       - secretName: letsencrypt
         hosts:
           - wwe.${DOMAIN}
  serviceName: wwe
  deployment:
    type: Deployment
    replicaCount: 3
    minReplicas: 1
    maxReplicas: 10
    strategy: {}
  annotations: {}
  livenessProbe:
    httpGet:
      path: /index.html
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /index.html
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
    timeoutSeconds: 5
  context:
    envs:
      optimizedConfig: false
      gwsUrl: https://gws.${DOMAIN}
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 6Gi
  priorityClassName:
  affinity: {}
  nodeSelector: {}
    #genesysengage.com/nodepool: {}
  tolerations: []
  labels: {}
  autoscaling:
    enabled: true
    targetCPUUtilizationPercentage: 40
    targetMemoryUtilizationPercentage: 80
