###############################################################################
#
# Find more: https://github.com/helm/charts/tree/master/stable/mssql-linux
#
###############################################################################

acceptEula:
  value: "y"

edition:
  value: "Developer"

persistence:
  enabled: true
  # existingDataClaim:
  # existingTransactionLogClaim:
  # existingBackupClaim:
  # existingMasterClaim:
  # storageClass: "-"
  dataAccessMode: ReadWriteOnce
  dataSize: 1Gi
  logAccessMode: ReadWriteOnce
  logSize: 1Gi
  backupAccessMode: ReadWriteOnce
  backupLogSize: 1Gi
  masterAccessMode: ReadWriteOnce
  masterSize: 1Gi

securityContext:
  fsGroup: 10001

agent:
  enabled: true