gws-app-provisioning: 9.0.001.05
gws-app-workspace: 9.0.001.00
gws-platform-configuration: 9.0.000.91
gws-platform-datacollector: 9.0.000.60
gws-platform-ixn: 9.0.000.53
gws-platform-ocs: 9.0.000.56
gws-platform-setting: 9.0.000.62
gws-platform-statistics: 9.0.000.71
gws-platform-voice: 9.0.000.76
gws-system-nginx: 9.0.000.26
gws-ui-crmworkspace: 9.0.000.72
gws-ui-provisioning: 9.0.000.96
gws-platform-ucs: 9.0.000.52
gws-platform-chat: 9.0.000.54

deploymentGlobals:
  # Location of the deployment
  location: global_location

gwsServices:
  gwsPlatformConfiguration:
    clientId: gws_client_id
  gwsPlatformDatacollector:
    clientId: gws_client_id
  gwsAppWorkspace:
    clientId: gws_client_id
  gwsPlatformIxn:
    clientId: gws_client_id
  gwsPlatformOcs:
    clientId: gws_client_id
  gwsPlatformSetting:
    clientId: gws_client_id
  gwsAppProvisioning:
    clientId: gws_client_id
    # PostgreSQL connection info for Agent Setup
    postgres:
      # PostgreSQL hostname
      address: POSTGRES_ADDR
      # PostgreSQL port
      port: 5432
      # PostgreSQL database name
      db: DB_NAME_PROV

### 3rd Party services
postgres:
  # FQDN or IP of PostgreSQL server
  address: POSTGRES_ADDR
  # Database name
  db: DB_NAME_GWS

elasticSearch:
  # FQDN or IP of ElasticSearch cluster
  address: ES_ADDR
  # ElasticSearch port
  port: 9200
  # Enable/disable TLS connection to Elasticsearch cluster
  enableTls: false

redis:
  # Redis cluster host name
  address: REDIS_ADDR
  # Redis port
  port: 6379
  # Enable/disable TLS connection to Redis cluster
  enableTls: false

# Secrets that should be provided to GWS components:
secrets:
  # public-secret
  gws-screen-recording-public-secret: test
  # private-secret
  gws-screen-recording-private-secret: test

###############################################################################
# Values below recommended to save in secrets/deployment-secrets for privacy 
# 
# Don`t change values below if using secrets/deployment-secrets. 
# It will be read and replaced by values from secrets/deployment-secrets
###############################################################################

  # Password to access Redis cluster
  gws-redis-password: gws_redis_password
  # API token to access Consul
  gws-consul-token: gws_consul_token
  # Username to access PostgreSQL database
  gws-postgres-username: gws_pg_user
  # Password to access PostgreSQL database
  gws-postgres-password: gws_pg_pass
  # Username to access PostgreSQL database  for Agent Setup
  agentsetup-postgres-username: gws_as_pg_user
  # Password to access PostgreSQL database for Agent Setup
  agentsetup-postgres-password: gws_as_pg_pass
  # Encrypted client secret generated by GAUTH service for the gws-app-provisioning component
  gws-app-provisioning-client-secret: gws_app_provisioning
  # Encrypted client secret generated by GAUTH service for the gws-app-workspace component
  gws-app-workspace-client-secret: gws_app_workspace
  # Encrypted client secret generated by GAUTH service for the gws-platform-configuration component
  gws-platform-configuration-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-datacollector component
  gws-platform-datacollector-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ixn component
  gws-platform-ixn-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ocs component
  gws-platform-ocs-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-setting component
  gws-platform-setting-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-statistics component
  gws-platform-statistics-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-voice component
  gws-platform-voice-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-chat component
  gws-platform-chat-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ucs component
  gws-platform-ucs-client-secret: gws_client_secret
  # Username of an operational user
  ops-username: gws_ops_user
  # Encrypted password of the operational user
  ops-password: gws_ops_pass_encr    
