gws-app-provisioning:       9.0.000.99
gws-app-workspace:          9.0.000.94
gws-platform-configuration: 9.0.000.84
gws-platform-datacollector: 9.0.000.54
gws-platform-ixn:           9.0.000.47
gws-platform-ocs:           9.0.000.50
gws-platform-setting:       9.0.000.56
gws-platform-statistics:    9.0.000.65
gws-platform-voice:         9.0.000.70
gws-ui-crmworkspace:        9.0.000.66
gws-ui-provisioning:        9.0.000.90
gws-ui-workspace:           9.0.000.87



postgres:
  address:  pg-gcpe-gke1.postgres.svc.cluster.local
  db:       gws-test

# Secrets that should be provided to GWS components:
secrets:
  gws-screen-recording-public-secret: test
  gws-screen-recording-private-secret: test

###############################################################################
# Values below recommended to save in secrets/deployment-secrets for pricacy 
# 
# Don`t change values below if using secrets/deployment-secrets. 
# It will be readed and replace by values from secrets/deployment-secrets
###############################################################################

  # Password to access Redis cluster
  gws-redis-password: gws_redis_password
  # API token to access Consul
  gws-consul-token: gws_consul_token
  # Username to access PostgreSQL database
  gws-postgres-username: gws_pg_user
  # Password to access PostgreSQL database
  gws-postgres-password: gws_pg_pass
  # Username to access PostgreSQL database  for Agent Setup
  agentsetup-postgres-username: gws_as_pg_user
  # Password to access PostgreSQL database for Agent Setup
  agentsetup-postgres-password: gws_as_pg_pass
  # Encrypted client secret generated by GAUTH service for the gws-app-provisioning component
  gws-app-provisioning-client-secret: gws_app_provisioning
  # Encrypted client secret generated by GAUTH service for the gws-app-workspace component
  gws-app-workspace-client-secret: gws_app_workspace
  # Encrypted client secret generated by GAUTH service for the gws-platform-configuration component
  gws-platform-configuration-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-datacollector component
  gws-platform-datacollector-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ixn component
  gws-platform-ixn-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ocs component
  gws-platform-ocs-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-setting component
  gws-platform-setting-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-statistics component
  gws-platform-statistics-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-voice component
  gws-platform-voice-client-secret: gws_client_secret
  # Username of an operational user
  ops-username: gws_ops_user
  # Encrypted password of the operational user
  ops-password: gws_ops_pass_encr


gwsServices:
  gws-platform-configuration:
    clientId: gws_client_id
  gws-platform-datacollector:
    clientId: gws_client_id
  gws-app-workspace:
    clientId: gws_client_id
  gws-platform-ixn:
    clientId: gws_client_id
  gws-platform-ocs:
    clientId: gws_client_id
  gws-platform-setting:
    clientId: gws_client_id
  gws-app-provisioning:
    clientId: gws_client_id
    postgres:
      address: pg-gcpe-gke1.postgres.svc.cluster.local
      port: 5432
      db: prov-test
    context:
      env:
        GWS_PROVISIONING_OBJECTCACHE_POSTGRES_HOST: pg-gcpe-gke1.postgres.svc.cluster.local    