# üíÅ The MicroK8s CPE workflow will:
# - Parse inputs: service for deployment, namespace, helm-repo, command
# - Check for required secrets
# - Checkout your repository
# - Install kubectl cli and helm chart tools
# - Add helm repository
# - Perform kubectl cluster login
# - Perform helm install/install/validate for service

# ‚ÑπÔ∏è Configure your repository and the workflow with the following steps:
# 1. Have access to an MicroK8s cluster. Refer to https://microk8s.io/docs/working-with-kubectl
# 2. Create the MK8S_CONFIG_FILE and IMAGE_REGISTRY_TOKEN (optional HELM_REGISTRY_TOKEN) repository secrets. Refer to:
#   - https://docs.github.com/en/actions/reference/encrypted-secrets
#   - https://cli.github.com/manual/gh_secret_set
# 3. (Optional) Edit the top-level 'env' section as marked with 'üñäÔ∏è' if the defaults are not suitable for your project.
# 5. Commit and push the workflow file to your default branch. Manually trigger a workflow run.

# üìÉ Considerations
# Pull secret should exist in coresponding namespace before workflow run.
# Create it by:    
#     kubectl create secret docker-registry pullsecret \
#       --docker-server=$IMAGE_REGISTRY \
#       --docker-username=user --docker-password=token




name: Deploy service to MicroK8s

env:
  # üñäÔ∏è EDIT your repository secrets to log into your MicroK8s cluster and set up the context.
  MK8S_SERVER:   "mk8s.dev"

  # üñäÔ∏è EDIT to change the helm registry settings.
  # Registries such as Jfrog, GHCR, Quay.io, and Docker Hub are supported.
  HELM_REGISTRY:            ${{ secrets.HELM_REGISTRY }}
  HELM_REGISTRY_USER:       ${{ secrets.HELM_REGISTRY_USER }}          
  HELM_REGISTRY_TOKEN:      ${{ secrets.HELM_REGISTRY_TOKEN }}
  IMAGE_REGISTRY:           ${{ secrets.IMAGE_REGISTRY }}


on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: service(s) for deployment
        required: true
        default: infra
        options:
        - infra
        - logging
        - monitoring
        - gauth
        - voice
        - tenant
        - gws
        - wwe        
        - webrtc
        - webrtc-blue-green
        - gvp
        - gsp
        - gim
        - gca
        - designer
        - designer-blue-green
        - ucsx
        - tlm
        - nexus
        - iwd
        - iwdem
        - iwddm
        - cxc
        - ges
        - pulse
        - bds
        - ixn
        - gcxi
      namespace:
        # by default will use namespace equal to service name
        description: namespace (if not default)
        required: false
      helmrepo:
        description: helm repo name in HELM_REGISTRY
        required: true
        default: helm-stage
      command:
        description: command install|validate|uninstall
        required: true
        default: validate
        
jobs:
  mk8s-ci-cd:
    name: Deploy ${{ github.event.inputs.service }} (${{ github.event.inputs.command }}) to mk8s
     # üñäÔ∏è (Optional) EDIT if you want to run on your own runner
     # We run runner in the same mk8s cluster
    runs-on: [ "self-hosted", "mk8s-runner"]

    steps:
    - name: Check for required secrets
      uses: actions/github-script@v4
      with:
        script: |
          const secrets = {
            MK8S_CONFIG_FILE: `${{ secrets.MK8S_CONFIG_FILE }}`,
            HELM_REGISTRY_TOKEN: `${{ secrets.HELM_REGISTRY_TOKEN }}`,
          };

          const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
            if (value.length === 0) {
              core.error(`Secret "${name}" is not set`);
              return true;
            }
            core.info(`‚úîÔ∏è Secret "${name}" is set`);
            return false;
          });

          if (missingSecrets.length > 0) {
            core.setFailed(`‚ùå At least one required secret is not set in the repository. \n` +
              "You can add it using:\n" +
              "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
              "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
              "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
          }
          else {
            core.info(`‚úÖ All the required secrets are set`);
          }


    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install kubectl CLI tool for MicroK8s
      uses: azure/setup-kubectl@v1
      with:
        # üñäÔ∏è (Optional) EDIT if you want to specify kubectl cli version
        version: "latest"


    - name: Set login context for kubectl
      uses: azure/k8s-set-context@v1
      with:
        # üñäÔ∏è Set MK8S_CONFIG_FILE in your github secrets
        # (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        # Generate secret content by command on microk8s cluster: $ microk8s config
        kubeconfig: ${{ secrets.MK8S_CONFIG_FILE }} 


    - name: Check helm version
      id: helm-version
      run: helm version
      continue-on-error: true


    # Installing helm if not pre-installed on runner
    - name: Install helm tool
      if: steps.helm-version.outcome == 'failure'
      uses: azure/setup-helm@v1
      #with:
        # üñäÔ∏è (Optional) EDIT if you want to specify helm version (default: "latest")
        #version: "v3.7.1"


    - name: Helm repo add
      run: |
        helm repo add --force-update helm_repo ${{ env.HELM_REGISTRY }}${{ github.event.inputs.helmrepo }} \
          --username ${{ env.HELM_REGISTRY_USER }} --password ${{ env.HELM_REGISTRY_TOKEN }}


    - name: Check config file mk8s and set kubectl context
      run: |
        echo "Connectivity check"
        if ! kubectl get nodes; then 
          echo "Login error using kube_mk8s_config"
          echo "Recommendation: verify your MK8S_CONFIG_FILE secret"
          exit 1
        fi 


    - name: Determine target namespace
      run: |
        NS=${{ github.event.inputs.namespace }}
        # By default (if namespace not defined) we install in namespace=service_name
        if [ -z "$NS" ] ; then
          NS=${{ github.event.inputs.service }}
          [[ $SV == "tenant" ]] && NS="voice"  # Tenant is exception, we deploy it in voice namespace by default
        fi
        echo "NS=$NS" >> $GITHUB_ENV


    - name: Create or use namespace
      run: |
        NS="${{ env.NS }}"
        if ! kubectl get namespace $NS; then
           echo "Namespace $NS does not exist. Creating it.."
           kubectl create namespace $NS
        else
           echo "Namespace $NS already exists. Will use it."
        fi
        kubectl config set-context --current --namespace=$NS


    - name: Custom script
      run: |
        export NS="${{ env.NS }}"
        export SERVICE=${{ github.event.inputs.service }}
        export DOMAIN=${{ env.MK8S_SERVER }}
        export IMAGE_REGISTRY=${{ env.IMAGE_REGISTRY }}

        cd $SERVICE

        FULLCOMMAND="${{ github.event.inputs.command }}"
        COMMAND=$(echo $FULLCOMMAND | cut -d' ' -f1)
        if [[ "$FULLCOMMAND" == *" "* ]]; then
          CHART_NAME=$(echo $FULLCOMMAND | tr -s ' ' | cut -d' ' -f2)
          RL_NAME=$(echo $FULLCOMMAND | tr -s ' ' | cut -d' ' -f3)
        fi

        # FOR EVERY HELM CHART ############################################################
        # ‚ÑπÔ∏è Notice: in application folder should be exist subfolder with name in format: 
        #      [0-9][0-9]_chart_chart-name 
        # where chart-name is name of chart using to installing 
        # and digits define the instalation order 
        # The chart-name using in command:
        #     helm install RELEASE-NAME helm-repo/chart-name
        # ##################################################################################
        for DIR_CH in [0-9][0-9]_chart_*$CHART_NAME*/; do
          
          CHART=$([[ -d "$DIR_CH" ]] && echo $DIR_CH | sed 's/[0-9][0-9]_chart_//' | sed 's/\///')
          
          DIR_CH=$(echo $DIR_CH | sed 's/\///')
          
          # evaluate ENV variables
          envsubst < $DIR_CH/override_values.yaml > overrides.yaml

          # üñäÔ∏è (Optional) EDIT 1st line of chart.ver file with chart version number
          VER=$(head -n 1 $DIR_CH/chart.ver)
          
          FLAGS="helm_repo/$CHART --install --version=$VER -n $NS -f $(pwd)/overrides.yaml"
          
          case $COMMAND in

            install)
              echo "Installing..."
              CMD="upgrade"
              ;;

            uninstall)
              echo "Uninstalling..."
              CMD="uninstall"
              FLAGS=""
              ;;

            validate)
              echo "Validating..."
              CMD="upgrade"
              FLAGS+=" --dry-run"
              ;;

            *)
              echo "‚ùå Wrong command"
              exit 1
              ;;

          esac

          cd $DIR_CH
          
          touch overrides.yaml
          [[ "$FLAGS" ]] && FLAGS+=" -f $(pwd)/overrides.yaml"
            
          # FOR EVERY HELM RELEASE###########################################################
          # ‚ÑπÔ∏è Notice: in chart folder you should have subfolder with name in format: 
          #      [0-9][0-9]_release_<release-name>
          # where release-name is name of release using to installing 
          # and digits define the instalation order 
          # The release-name using in command:
          #     helm install release-name helm-repo/chart-name
          #
          # If you want to run some preparing script (for ex: init database, check conditions) 
          # before installing, place you code in pre-relese-script.sh in release subfolder
          #
          # If you want to run some post-installing script (for ex: validate something),
          # place you code in post-relese-script.sh in release subfolder
          # ##################################################################################
          for DIR_RL in [0-9][0-9]_release_*$RL_NAME*/; do

                RELEASE=$([[ -d "$DIR_RL" ]] && echo $DIR_RL | sed 's/[0-9][0-9]_release_//' | sed 's/\///')

                cd $DIR_RL
                # Run pre-release-script if exists
                [[ "$COMMAND" == "install" ]] && [[ -f "pre-release-script.sh" ]] \
                  && source pre-release-script.sh
                cd ..

                # evaluate ENV variables
                envsubst < $DIR_RL/override_values.yaml > overrides.yaml


                echo "helm $CMD $RELEASE $FLAGS"
                [[ "$CMD" ]] && [[ "$CHART" ]] && [[ "$RELEASE" ]] && \
                            helm $CMD $RELEASE $FLAGS

                cd $DIR_RL
                # Run post-release-script if exists
                [[ "$COMMAND" == "install" ]] && [[ -f "post-release-script.sh" ]] \
                  && source post-release-script.sh
                cd ..
          
          done

          cd ..

        done


    - name: Reset to default kubectl context
      run: |
        export KUBECONFIG=
