imageGlobals:
  # Docker registry address
  registry: repository.path/gws
  # Specifies whether chart will pull images
  pullPolicy: Always
  # Secrets for pulling image
  imagePullSecrets:
    - name: pullsecret

deploymentGlobals:
  deploymentTag: blue
  # Location of the deployment
  location: /USW1
  # Specifies the default security context for all pods
  securityContext:
    # Whether a container must run as a non-root user
    runAsNonRoot: true
    # The UID to run the entrypoint of the container process
    runAsUser: null
    # The GID to run the entrypoint of the container process
    runAsGroup: 0
    # A supplemental group ID that applies to all containers in a pod
    fsGroup: null

# DNS configuration
dnsConfig:
  options:
  - name: ndots
    value: "3"

gwsServices:
  gws-app-provisioning:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 1
        memory: 3200Mi
      requests:
        cpu: 0.5
        memory: 3200Mi

    context:
      env:
        GWS_PROVISIONING_COMMON_LOGLEVEL: info
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_CONF_URL: http://gws-service-proxy.gws.svc.cluster.local:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_SERVICE_VOICEMAIL_URL: http://voice-voicemail-service.voice.svc.cluster.local.:8081/fs
        # Enables/disables SSL connection to PostgreSQL. Possible values: disable, prefer, require, verify-ca, verify-full
        PGSSLMODE: disable
        GWS_PROVISIONING_OBJECTCACHE_DB_TYPE: postgres
        GWS_PROVISIONING_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        WS_PROVISIONING_OBJECTCACHE_POSTGRES_USER: prov
        GWS_PROVISIONING_OBJECTCACHE_POSTGRES_PASSWORD: prov
        GWS_PROVISIONING_OBJECTCACHE_POSTGRES_PORT: 5432
        GWS_PROVISIONING_OBJECTCACHE_POSTGRES_USE_SSL: false
        GWS_SECURE_COOKIE: false

  gws-app-workspace:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_WORKSPACE_SERVER_USE_SECURE_COOKIE: true
        GWS_SECURE_COOKIE: true
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_SERVICE_VOICEMAIL_URL: http://voice-voicemail-service.voice.svc.cluster.local.:8081/fs
        GWS_WORKSPACE_SERVICES_ENV: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_WORKSPACE_SERVICES_AUTH: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_WORKSPACE_CONSUL_AUTH_ENV_DISABLED: true
        #GWS_WORKSPACE_SERVER_USE_SECURE_COOKIE: true

  gws-platform-configuration:

    deployment:
      # Number of pod replicas
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_CONFIGURATION_COMMON_DISCOVERY_TENANTS: true
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_CONFIGURATION_timeouts_environmentRefreshMs: 300000
        GWS_CONFIGURATION_cache_tenantRefreshIntervalMin: 1

  gws-platform-datacollector:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_DATACOLLECTOR_timeouts_environmentRefreshMs: 300000

  gws-platform-ixn:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_IXN_COMMON_ENV_SERVICE: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_IXN_COMMON_AUTH_SERVICE: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_IXN_timeouts_environmentRefreshMs: 60000

  gws-platform-ocs:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_OCS_timeouts_environmentRefreshMs: 300000
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80

  gws-platform-setting:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_SETTING_COMMON_ENV_SERVICE: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_SETTING_COMMON_AUTH_SERVICE: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_SETTING_timeouts_environmentRefreshMs: 300000
        #GWS_SETTING_db_readOnly: true

  gws-platform-statistics:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_STATISTICS_timeouts_environmentRefreshMs: 300000

  gws-platform-voice:

    deployment:
      replicaCount: 1

    resources:
      limits:
        cpu: 0.8
        memory: 700Mi
      requests:
        cpu: 0.4
        memory: 500Mi

    context:
      env:
        GWS_WORKSPACE_SERVICES_AUTH_FOR_REDIRECT: https://gauth.${DOMAIN}
        GWS_SERVICE_AUTH_URL: http://gauth-auth.gauth.svc.cluster.local.:80
        GWS_SERVICE_ENV_URL: http://gauth-environment.gauth.svc.cluster.local.:80
        GWS_VOICE_timeouts_requestTimeoutMs: 30000
        GWS_VOICE_timeouts_environmentRefreshMs: 10000
        #GWS_PSDK_ENHANCED_PROTOCOL_SECURITY: true

  gws-ui-crmworkspace:
    deployment:
      replicaCount: 1

  gws-ui-provisioning:
    deployment:
      replicaCount: 1

  gws-ui-workspace:
    deployment:
      replicaCount: 1

### 3-d Party services

elasticSearch:
  # FQDN or IP of ElasticSearch cluster
  address: elastic-es-http.infra-test.svc.cluster.local
  # ElasticSearch port
  port: 9200
  # Enable/disable TLS connection to Elasticsearch cluster
  enableTls: false


redis:
  # Redis cluster host name
  address: infra-redis-redis-cluster.infra-test.svc.cluster.local
  # Redis port
  port: 6379
  # Enable/disable TLS connection to Redis cluster
  enableTls: false

consul:
  # Port of local Consul agent
  port: 8500
  # Prefix to locate GWS data in the Consul KV storage
  kv_prefix: "gws-test"

prometheus:
  # Enables annotation based discovery to scrape metrics
  metricServer:
    enabled: true

gwsServiceProxy:
  context:
    sessionCookieName: GWSLB
