# Default values for init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  registry: "$IMAGE_REGISTRY"
  imagePullSecrets:
    - name: pullsecret

# common configuration.
config:
  # set "true" to create config maps
  createConfigMap: true
  # set "true" to create secrets
  createSecret: true

  # Postgres config
  # Postgres config map name
  postgresConfig: "pulse-postgres-configmap"
  # Postgres hostname
  postgresHost: "postgres-rw.infra.svc.cluster.local"
  # Postgres port
  postgresPort: "5432"
  # Postgres SSL mode
  postgresEnableSSL: "prefer"
  # Postgres User
  postgresUser: "postgres_user"
  # Postgres Password
  postgresPassword: "postgres_password"
  # Secret name for postgres
  postgresSecret: "pulse-postgres-secret"
  # Secret key for postgres user
  postgresSecretUser: "META_DB_ADMIN"
  # Secret key for postgres  password
  postgresSecretPassword: "META_DB_ADMINPWD"

  # fill database name
  dbName: "pulse"
  # set "true" when need @host added for username
  dbUserWithHost: false

  # Redis config
  # Redis config map name
  redisConfig: "pulse-redis-configmap"
  # Redis host
  redisHost: "pulse-redis-master.${NS}.cluster.local"
  # Redis port
  redisPort: "6379"
  # Redis SSL enabled
  redisEnableSSL: "false"
  # Password for Redis
  redisKey: "redis_key"
  # Secret name for Redis
  redisSecret: "pulse-redis-secret"
  # Secret key for Redis password
  redisSecretKey: "REDIS01_KEY"

  # GWS config
  # Client ID
  gwsClientId: "gws_ClientId"
  # Client Secret
  gwsClientSecret: "gws_Client_Secret"
  # Secret name
  gwsSecret: "pulse-gws-secret"
  # Secret key for Client ID
  gwsSecretClientId: "clientId"
  # Secret key for Client Secret
  gwsSecretClientSecret: "clientSecret"


  # set "true" for CSI secrets
  mountSecrets: false

## Service account settings
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Add annotations to all pods
##
podAnnotations: {}

## Resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m

## Priority Class
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
priorityClassName: ""

## Node labels for assignment.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for assignment.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
