###############################################################################
# Global ucsx-addtenent image parameters
# https://all.docs.genesys.com/UCS/Current/UCSPEGuide/Provision
###############################################################################

image:
  registry: $IMAGE_REGISTRY
  pullSecrets: 
    - name: pullsecret

command: "register_ucsx_tenant" #"unregister_ucsx_tenant" 
       
ucsx:
  addr: ucsx.${NS}.svc:8500
  restaddr: http://ucsx.${DOMAIN}

configNameBase: ucsx-config
secretNameBase: ucsx-secret

keepPod: true

wwe:
  restMode: true

gauth:
  auth:
    url: http://gauth-auth.gauth.svc
  env:
    url: http://gauth-environment.gauth.svc

resources: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 500
  runAsGroup: 500
  fsGroup: 500

ingress:
  enabled: true
  hosts:
  - host: ucsx.${DOMAIN}
    paths:
    - path: /ucs/v3/
      port: 8080
    - path: /ucs/v10/
      port: 8080
    - path: /ucs/v3/config
      port: 8500
