# Additional override values

image:
  snmptag: 100.0.100.0039

context:
  env:
    GVP_RS_SERVICE_HOSTNAME: gvp-rs.gvp.svc.cluster.local
    CFG_HOST: gvp-configserver.gvp.svc.cluster.local
    DBUSER: survey
    rsDbSharedUsername: portal
    MSSQLHOST: 192.168.30.60
